---
name: Build and Push GCP Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    env:
      IMAGE_NAME: client
      PROJECT_ID: devopsbyexample-325402
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Build Docker Google Cloud Build
      run: gcloud builds submit --tag gcr.io/$IMAGE_NAME/$IMAGE_NAME --project $IMAGE_NAME 

    - name: Deploy Google Cloud Build
      run: gcloud run deploy --image gcr.io/$IMAGE_NAME/$IMAGE_NAME --project $IMAGE_NAME --platform managed
